version: "3.4"

services:
    api:
        build: .
        command: uvicorn server.server:app --host 0.0.0.0 --port 8000 --no-access-log  --reload --log-level debug
        volumes:
            - .:/code
        ports:
            - 8000:8000
